export interface Course {
  id: string
  name: string
  code: string
  credits: number
  description: string
  prerequisites?: string[]
  type: "core" | "elective" | "lab" | "project"
}

export interface YearCurriculum {
  year: number
  semester1: Course[]
  semester2: Course[]
}

export interface EngineeringBranch {
  id: string
  name: string
  abbreviation: string
  description: string
  curriculum: YearCurriculum[]
  specializations?: string[]
}

export const engineeringCurriculum: Record<string, EngineeringBranch> = {
  "computer-science": {
    id: "computer-science",
    name: "Computer Science Engineering",
    abbreviation: "CSE",
    description: "Focuses on software development, algorithms, data structures, and computer systems",
    curriculum: [
      {
        year: 1,
        semester1: [
          {
            id: "ma101",
            name: "Engineering Mathematics I",
            code: "MA101",
            credits: 4,
            description: "Calculus, differential equations",
            type: "core",
          },
          {
            id: "ph101",
            name: "Engineering Physics I",
            code: "PH101",
            credits: 4,
            description: "Mechanics, waves, optics",
            type: "core",
          },
          {
            id: "ch101",
            name: "Engineering Chemistry",
            code: "CH101",
            credits: 3,
            description: "Basic chemistry principles",
            type: "core",
          },
          {
            id: "cs101",
            name: "Programming Fundamentals",
            code: "CS101",
            credits: 4,
            description: "Introduction to programming with C",
            type: "core",
          },
          {
            id: "me101",
            name: "Engineering Graphics",
            code: "ME101",
            credits: 3,
            description: "Technical drawing and CAD",
            type: "core",
          },
          {
            id: "hs101",
            name: "English Communication",
            code: "HS101",
            credits: 2,
            description: "Technical writing and communication",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ma102",
            name: "Engineering Mathematics II",
            code: "MA102",
            credits: 4,
            description: "Linear algebra, vector calculus",
            type: "core",
          },
          {
            id: "ph102",
            name: "Engineering Physics II",
            code: "PH102",
            credits: 4,
            description: "Electricity, magnetism, modern physics",
            type: "core",
          },
          {
            id: "ee101",
            name: "Basic Electrical Engineering",
            code: "EE101",
            credits: 3,
            description: "Circuit analysis, electrical machines",
            type: "core",
          },
          {
            id: "cs102",
            name: "Data Structures",
            code: "CS102",
            credits: 4,
            description: "Arrays, linked lists, stacks, queues",
            type: "core",
          },
          {
            id: "cs103",
            name: "Digital Logic Design",
            code: "CS103",
            credits: 3,
            description: "Boolean algebra, logic gates",
            type: "core",
          },
          {
            id: "hs102",
            name: "Environmental Science",
            code: "HS102",
            credits: 2,
            description: "Environmental awareness",
            type: "core",
          },
        ],
      },
      {
        year: 2,
        semester1: [
          {
            id: "ma201",
            name: "Discrete Mathematics",
            code: "MA201",
            credits: 4,
            description: "Graph theory, combinatorics",
            type: "core",
          },
          {
            id: "cs201",
            name: "Object Oriented Programming",
            code: "CS201",
            credits: 4,
            description: "OOP concepts with Java/C++",
            type: "core",
          },
          {
            id: "cs202",
            name: "Computer Organization",
            code: "CS202",
            credits: 4,
            description: "CPU architecture, memory systems",
            type: "core",
          },
          {
            id: "cs203",
            name: "Database Management Systems",
            code: "CS203",
            credits: 4,
            description: "Relational databases, SQL",
            type: "core",
          },
          {
            id: "ma202",
            name: "Probability and Statistics",
            code: "MA202",
            credits: 3,
            description: "Statistical analysis for CS",
            type: "core",
          },
          {
            id: "cs204",
            name: "Programming Lab",
            code: "CS204",
            credits: 2,
            description: "Hands-on programming practice",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "cs205",
            name: "Algorithms",
            code: "CS205",
            credits: 4,
            description: "Algorithm design and analysis",
            type: "core",
          },
          {
            id: "cs206",
            name: "Operating Systems",
            code: "CS206",
            credits: 4,
            description: "Process management, memory management",
            type: "core",
          },
          {
            id: "cs207",
            name: "Computer Networks",
            code: "CS207",
            credits: 4,
            description: "Network protocols, OSI model",
            type: "core",
          },
          {
            id: "cs208",
            name: "Software Engineering",
            code: "CS208",
            credits: 3,
            description: "SDLC, project management",
            type: "core",
          },
          {
            id: "cs209",
            name: "Theory of Computation",
            code: "CS209",
            credits: 3,
            description: "Automata, formal languages",
            type: "core",
          },
          {
            id: "cs210",
            name: "Database Lab",
            code: "CS210",
            credits: 2,
            description: "SQL and database implementation",
            type: "lab",
          },
        ],
      },
      {
        year: 3,
        semester1: [
          {
            id: "cs301",
            name: "Compiler Design",
            code: "CS301",
            credits: 4,
            description: "Lexical analysis, parsing",
            type: "core",
          },
          {
            id: "cs302",
            name: "Computer Graphics",
            code: "CS302",
            credits: 4,
            description: "2D/3D graphics, rendering",
            type: "core",
          },
          {
            id: "cs303",
            name: "Artificial Intelligence",
            code: "CS303",
            credits: 4,
            description: "AI algorithms, machine learning basics",
            type: "core",
          },
          {
            id: "cs304",
            name: "Web Technologies",
            code: "CS304",
            credits: 3,
            description: "HTML, CSS, JavaScript, frameworks",
            type: "elective",
          },
          {
            id: "cs305",
            name: "Cybersecurity",
            code: "CS305",
            credits: 3,
            description: "Network security, cryptography",
            type: "elective",
          },
          {
            id: "cs306",
            name: "Graphics Lab",
            code: "CS306",
            credits: 2,
            description: "Graphics programming",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "cs307",
            name: "Machine Learning",
            code: "CS307",
            credits: 4,
            description: "Supervised/unsupervised learning",
            type: "core",
          },
          {
            id: "cs308",
            name: "Distributed Systems",
            code: "CS308",
            credits: 4,
            description: "Distributed computing concepts",
            type: "core",
          },
          {
            id: "cs309",
            name: "Mobile App Development",
            code: "CS309",
            credits: 3,
            description: "Android/iOS development",
            type: "elective",
          },
          {
            id: "cs310",
            name: "Cloud Computing",
            code: "CS310",
            credits: 3,
            description: "Cloud platforms and services",
            type: "elective",
          },
          {
            id: "cs311",
            name: "Data Mining",
            code: "CS311",
            credits: 3,
            description: "Data analysis and mining techniques",
            type: "elective",
          },
          {
            id: "cs312",
            name: "ML Lab",
            code: "CS312",
            credits: 2,
            description: "Machine learning implementation",
            type: "lab",
          },
        ],
      },
      {
        year: 4,
        semester1: [
          {
            id: "cs401",
            name: "Deep Learning",
            code: "CS401",
            credits: 4,
            description: "Neural networks, deep architectures",
            type: "elective",
          },
          {
            id: "cs402",
            name: "Blockchain Technology",
            code: "CS402",
            credits: 3,
            description: "Cryptocurrency, smart contracts",
            type: "elective",
          },
          {
            id: "cs403",
            name: "IoT and Embedded Systems",
            code: "CS403",
            credits: 3,
            description: "Internet of Things applications",
            type: "elective",
          },
          {
            id: "cs404",
            name: "Software Architecture",
            code: "CS404",
            credits: 3,
            description: "Design patterns, microservices",
            type: "elective",
          },
          {
            id: "cs405",
            name: "Capstone Project I",
            code: "CS405",
            credits: 4,
            description: "Major project work",
            type: "project",
          },
          {
            id: "hs401",
            name: "Professional Ethics",
            code: "HS401",
            credits: 2,
            description: "Engineering ethics",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "cs406",
            name: "Quantum Computing",
            code: "CS406",
            credits: 3,
            description: "Quantum algorithms and computing",
            type: "elective",
          },
          {
            id: "cs407",
            name: "DevOps and Automation",
            code: "CS407",
            credits: 3,
            description: "CI/CD, containerization",
            type: "elective",
          },
          {
            id: "cs408",
            name: "Advanced Database Systems",
            code: "CS408",
            credits: 3,
            description: "NoSQL, distributed databases",
            type: "elective",
          },
          {
            id: "cs409",
            name: "Capstone Project II",
            code: "CS409",
            credits: 6,
            description: "Project completion and presentation",
            type: "project",
          },
          {
            id: "hs402",
            name: "Entrepreneurship",
            code: "HS402",
            credits: 2,
            description: "Business development",
            type: "elective",
          },
        ],
      },
    ],
    specializations: [
      "Artificial Intelligence",
      "Data Science",
      "Cybersecurity",
      "Software Engineering",
      "Cloud Computing",
    ],
  },

  electrical: {
    id: "electrical",
    name: "Electrical Engineering",
    abbreviation: "EE",
    description: "Focuses on electrical systems, power generation, and electronics",
    curriculum: [
      {
        year: 1,
        semester1: [
          {
            id: "ma101",
            name: "Engineering Mathematics I",
            code: "MA101",
            credits: 4,
            description: "Calculus, differential equations",
            type: "core",
          },
          {
            id: "ph101",
            name: "Engineering Physics I",
            code: "PH101",
            credits: 4,
            description: "Mechanics, waves, optics",
            type: "core",
          },
          {
            id: "ch101",
            name: "Engineering Chemistry",
            code: "CH101",
            credits: 3,
            description: "Basic chemistry principles",
            type: "core",
          },
          {
            id: "ee101",
            name: "Electrical Fundamentals",
            code: "EE101",
            credits: 4,
            description: "Basic electrical concepts",
            type: "core",
          },
          {
            id: "me101",
            name: "Engineering Graphics",
            code: "ME101",
            credits: 3,
            description: "Technical drawing",
            type: "core",
          },
          {
            id: "hs101",
            name: "English Communication",
            code: "HS101",
            credits: 2,
            description: "Technical communication",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ma102",
            name: "Engineering Mathematics II",
            code: "MA102",
            credits: 4,
            description: "Linear algebra, vector calculus",
            type: "core",
          },
          {
            id: "ph102",
            name: "Engineering Physics II",
            code: "PH102",
            credits: 4,
            description: "Electricity, magnetism",
            type: "core",
          },
          {
            id: "ee102",
            name: "Circuit Analysis",
            code: "EE102",
            credits: 4,
            description: "DC and AC circuit analysis",
            type: "core",
          },
          {
            id: "ee103",
            name: "Electronic Devices",
            code: "EE103",
            credits: 3,
            description: "Semiconductors, diodes, transistors",
            type: "core",
          },
          {
            id: "cs101",
            name: "Programming for Engineers",
            code: "CS101",
            credits: 3,
            description: "C programming basics",
            type: "core",
          },
          {
            id: "hs102",
            name: "Environmental Science",
            code: "HS102",
            credits: 2,
            description: "Environmental awareness",
            type: "core",
          },
        ],
      },
      {
        year: 2,
        semester1: [
          {
            id: "ma201",
            name: "Advanced Engineering Mathematics",
            code: "MA201",
            credits: 4,
            description: "Complex analysis, transforms",
            type: "core",
          },
          {
            id: "ee201",
            name: "Electromagnetic Fields",
            code: "EE201",
            credits: 4,
            description: "Maxwell's equations, wave propagation",
            type: "core",
          },
          {
            id: "ee202",
            name: "Analog Electronics",
            code: "EE202",
            credits: 4,
            description: "Amplifiers, operational amplifiers",
            type: "core",
          },
          {
            id: "ee203",
            name: "Electrical Machines I",
            code: "EE203",
            credits: 4,
            description: "DC machines, transformers",
            type: "core",
          },
          {
            id: "ee204",
            name: "Signals and Systems",
            code: "EE204",
            credits: 3,
            description: "Signal processing fundamentals",
            type: "core",
          },
          {
            id: "ee205",
            name: "Electronics Lab",
            code: "EE205",
            credits: 2,
            description: "Circuit implementation",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "ee206",
            name: "Digital Electronics",
            code: "EE206",
            credits: 4,
            description: "Logic design, sequential circuits",
            type: "core",
          },
          {
            id: "ee207",
            name: "Electrical Machines II",
            code: "EE207",
            credits: 4,
            description: "AC machines, special machines",
            type: "core",
          },
          {
            id: "ee208",
            name: "Control Systems",
            code: "EE208",
            credits: 4,
            description: "Feedback control, stability",
            type: "core",
          },
          {
            id: "ee209",
            name: "Network Analysis",
            code: "EE209",
            credits: 3,
            description: "Network theorems, two-port networks",
            type: "core",
          },
          {
            id: "ee210",
            name: "Measurement & Instrumentation",
            code: "EE210",
            credits: 3,
            description: "Electrical measurements",
            type: "core",
          },
          { id: "ee211", name: "Machines Lab", code: "EE211", credits: 2, description: "Machine testing", type: "lab" },
        ],
      },
      {
        year: 3,
        semester1: [
          {
            id: "ee301",
            name: "Power Systems I",
            code: "EE301",
            credits: 4,
            description: "Power generation, transmission",
            type: "core",
          },
          {
            id: "ee302",
            name: "Microprocessors",
            code: "EE302",
            credits: 4,
            description: "8085/8086 architecture",
            type: "core",
          },
          {
            id: "ee303",
            name: "Power Electronics",
            code: "EE303",
            credits: 4,
            description: "Converters, inverters",
            type: "core",
          },
          {
            id: "ee304",
            name: "Communication Systems",
            code: "EE304",
            credits: 3,
            description: "Analog/digital communication",
            type: "elective",
          },
          {
            id: "ee305",
            name: "Renewable Energy",
            code: "EE305",
            credits: 3,
            description: "Solar, wind energy systems",
            type: "elective",
          },
          {
            id: "ee306",
            name: "Power Electronics Lab",
            code: "EE306",
            credits: 2,
            description: "Converter circuits",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "ee307",
            name: "Power Systems II",
            code: "EE307",
            credits: 4,
            description: "Protection, stability",
            type: "core",
          },
          {
            id: "ee308",
            name: "VLSI Design",
            code: "EE308",
            credits: 4,
            description: "IC design, layout",
            type: "elective",
          },
          {
            id: "ee309",
            name: "Electric Drives",
            code: "EE309",
            credits: 3,
            description: "Motor control systems",
            type: "elective",
          },
          {
            id: "ee310",
            name: "Smart Grid Technology",
            code: "EE310",
            credits: 3,
            description: "Modern grid systems",
            type: "elective",
          },
          {
            id: "ee311",
            name: "Embedded Systems",
            code: "EE311",
            credits: 3,
            description: "Microcontroller applications",
            type: "elective",
          },
          {
            id: "ee312",
            name: "Power Systems Lab",
            code: "EE312",
            credits: 2,
            description: "System analysis",
            type: "lab",
          },
        ],
      },
      {
        year: 4,
        semester1: [
          {
            id: "ee401",
            name: "High Voltage Engineering",
            code: "EE401",
            credits: 3,
            description: "Insulation, lightning protection",
            type: "elective",
          },
          {
            id: "ee402",
            name: "Electric Vehicle Technology",
            code: "EE402",
            credits: 3,
            description: "EV systems and charging",
            type: "elective",
          },
          {
            id: "ee403",
            name: "Digital Signal Processing",
            code: "EE403",
            credits: 3,
            description: "DSP algorithms and applications",
            type: "elective",
          },
          {
            id: "ee404",
            name: "Project Management",
            code: "EE404",
            credits: 2,
            description: "Engineering project management",
            type: "core",
          },
          {
            id: "ee405",
            name: "Major Project I",
            code: "EE405",
            credits: 4,
            description: "Capstone project work",
            type: "project",
          },
          {
            id: "hs401",
            name: "Professional Ethics",
            code: "HS401",
            credits: 2,
            description: "Engineering ethics",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ee406",
            name: "Power Quality",
            code: "EE406",
            credits: 3,
            description: "Harmonics, power factor correction",
            type: "elective",
          },
          {
            id: "ee407",
            name: "Industrial Automation",
            code: "EE407",
            credits: 3,
            description: "PLC, SCADA systems",
            type: "elective",
          },
          {
            id: "ee408",
            name: "Energy Management",
            code: "EE408",
            credits: 3,
            description: "Energy audit, conservation",
            type: "elective",
          },
          {
            id: "ee409",
            name: "Major Project II",
            code: "EE409",
            credits: 6,
            description: "Project completion",
            type: "project",
          },
          {
            id: "hs402",
            name: "Entrepreneurship",
            code: "HS402",
            credits: 2,
            description: "Business development",
            type: "elective",
          },
        ],
      },
    ],
    specializations: ["Power Systems", "Power Electronics", "Control Systems", "Renewable Energy", "VLSI Design"],
  },

  mechanical: {
    id: "mechanical",
    name: "Mechanical Engineering",
    abbreviation: "ME",
    description: "Focuses on design, manufacturing, and mechanical systems",
    curriculum: [
      {
        year: 1,
        semester1: [
          {
            id: "ma101",
            name: "Engineering Mathematics I",
            code: "MA101",
            credits: 4,
            description: "Calculus, differential equations",
            type: "core",
          },
          {
            id: "ph101",
            name: "Engineering Physics I",
            code: "PH101",
            credits: 4,
            description: "Mechanics, properties of matter",
            type: "core",
          },
          {
            id: "ch101",
            name: "Engineering Chemistry",
            code: "CH101",
            credits: 3,
            description: "Basic chemistry for engineers",
            type: "core",
          },
          {
            id: "me101",
            name: "Engineering Graphics",
            code: "ME101",
            credits: 4,
            description: "Technical drawing, CAD basics",
            type: "core",
          },
          {
            id: "me102",
            name: "Workshop Technology",
            code: "ME102",
            credits: 3,
            description: "Manufacturing processes",
            type: "core",
          },
          {
            id: "hs101",
            name: "English Communication",
            code: "HS101",
            credits: 2,
            description: "Technical communication",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ma102",
            name: "Engineering Mathematics II",
            code: "MA102",
            credits: 4,
            description: "Linear algebra, vector calculus",
            type: "core",
          },
          {
            id: "ph102",
            name: "Engineering Physics II",
            code: "PH102",
            credits: 4,
            description: "Heat, thermodynamics basics",
            type: "core",
          },
          {
            id: "me103",
            name: "Engineering Mechanics",
            code: "ME103",
            credits: 4,
            description: "Statics, dynamics",
            type: "core",
          },
          {
            id: "me104",
            name: "Materials Science",
            code: "ME104",
            credits: 3,
            description: "Properties of engineering materials",
            type: "core",
          },
          {
            id: "ee101",
            name: "Basic Electrical Engineering",
            code: "EE101",
            credits: 3,
            description: "Electrical fundamentals",
            type: "core",
          },
          {
            id: "hs102",
            name: "Environmental Science",
            code: "HS102",
            credits: 2,
            description: "Environmental awareness",
            type: "core",
          },
        ],
      },
      {
        year: 2,
        semester1: [
          {
            id: "ma201",
            name: "Advanced Engineering Mathematics",
            code: "MA201",
            credits: 4,
            description: "Fourier series, partial differential equations",
            type: "core",
          },
          {
            id: "me201",
            name: "Strength of Materials",
            code: "ME201",
            credits: 4,
            description: "Stress, strain, beam theory",
            type: "core",
          },
          {
            id: "me202",
            name: "Thermodynamics I",
            code: "ME202",
            credits: 4,
            description: "Laws of thermodynamics",
            type: "core",
          },
          {
            id: "me203",
            name: "Manufacturing Processes",
            code: "ME203",
            credits: 4,
            description: "Casting, welding, machining",
            type: "core",
          },
          {
            id: "me204",
            name: "Computer Programming",
            code: "ME204",
            credits: 3,
            description: "Programming for engineers",
            type: "core",
          },
          {
            id: "me205",
            name: "Manufacturing Lab",
            code: "ME205",
            credits: 2,
            description: "Hands-on manufacturing",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "me206",
            name: "Fluid Mechanics",
            code: "ME206",
            credits: 4,
            description: "Fluid statics and dynamics",
            type: "core",
          },
          {
            id: "me207",
            name: "Thermodynamics II",
            code: "ME207",
            credits: 4,
            description: "Power cycles, refrigeration",
            type: "core",
          },
          {
            id: "me208",
            name: "Machine Design I",
            code: "ME208",
            credits: 4,
            description: "Design fundamentals",
            type: "core",
          },
          {
            id: "me209",
            name: "Kinematics of Machines",
            code: "ME209",
            credits: 3,
            description: "Mechanisms, velocity analysis",
            type: "core",
          },
          {
            id: "me210",
            name: "Metrology",
            code: "ME210",
            credits: 3,
            description: "Measurement and inspection",
            type: "core",
          },
          {
            id: "me211",
            name: "Fluid Mechanics Lab",
            code: "ME211",
            credits: 2,
            description: "Fluid flow experiments",
            type: "lab",
          },
        ],
      },
      {
        year: 3,
        semester1: [
          {
            id: "me301",
            name: "Heat Transfer",
            code: "ME301",
            credits: 4,
            description: "Conduction, convection, radiation",
            type: "core",
          },
          {
            id: "me302",
            name: "Dynamics of Machines",
            code: "ME302",
            credits: 4,
            description: "Force analysis, balancing",
            type: "core",
          },
          {
            id: "me303",
            name: "Machine Design II",
            code: "ME303",
            credits: 4,
            description: "Design of machine elements",
            type: "core",
          },
          {
            id: "me304",
            name: "Production Technology",
            code: "ME304",
            credits: 3,
            description: "Advanced manufacturing",
            type: "elective",
          },
          {
            id: "me305",
            name: "Automobile Engineering",
            code: "ME305",
            credits: 3,
            description: "Vehicle systems",
            type: "elective",
          },
          {
            id: "me306",
            name: "Heat Transfer Lab",
            code: "ME306",
            credits: 2,
            description: "Heat transfer experiments",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "me307",
            name: "Internal Combustion Engines",
            code: "ME307",
            credits: 4,
            description: "Engine cycles, performance",
            type: "core",
          },
          {
            id: "me308",
            name: "Vibrations",
            code: "ME308",
            credits: 4,
            description: "Free and forced vibrations",
            type: "core",
          },
          {
            id: "me309",
            name: "Operations Research",
            code: "ME309",
            credits: 3,
            description: "Optimization techniques",
            type: "elective",
          },
          {
            id: "me310",
            name: "Robotics",
            code: "ME310",
            credits: 3,
            description: "Robot kinematics, control",
            type: "elective",
          },
          {
            id: "me311",
            name: "Renewable Energy Systems",
            code: "ME311",
            credits: 3,
            description: "Solar, wind systems",
            type: "elective",
          },
          {
            id: "me312",
            name: "IC Engines Lab",
            code: "ME312",
            credits: 2,
            description: "Engine testing",
            type: "lab",
          },
        ],
      },
      {
        year: 4,
        semester1: [
          {
            id: "me401",
            name: "Finite Element Methods",
            code: "ME401",
            credits: 3,
            description: "FEA techniques",
            type: "elective",
          },
          {
            id: "me402",
            name: "HVAC Systems",
            code: "ME402",
            credits: 3,
            description: "Air conditioning systems",
            type: "elective",
          },
          {
            id: "me403",
            name: "Advanced Manufacturing",
            code: "ME403",
            credits: 3,
            description: "CNC, automation",
            type: "elective",
          },
          {
            id: "me404",
            name: "Engineering Economics",
            code: "ME404",
            credits: 2,
            description: "Economic analysis",
            type: "core",
          },
          {
            id: "me405",
            name: "Major Project I",
            code: "ME405",
            credits: 4,
            description: "Capstone project",
            type: "project",
          },
          {
            id: "hs401",
            name: "Professional Ethics",
            code: "HS401",
            credits: 2,
            description: "Engineering ethics",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "me406",
            name: "Mechatronics",
            code: "ME406",
            credits: 3,
            description: "Integrated mechanical systems",
            type: "elective",
          },
          {
            id: "me407",
            name: "Quality Engineering",
            code: "ME407",
            credits: 3,
            description: "Quality control, six sigma",
            type: "elective",
          },
          {
            id: "me408",
            name: "Project Management",
            code: "ME408",
            credits: 3,
            description: "Engineering project management",
            type: "elective",
          },
          {
            id: "me409",
            name: "Major Project II",
            code: "ME409",
            credits: 6,
            description: "Project completion",
            type: "project",
          },
          {
            id: "hs402",
            name: "Entrepreneurship",
            code: "HS402",
            credits: 2,
            description: "Business development",
            type: "elective",
          },
        ],
      },
    ],
    specializations: ["Thermal Engineering", "Design & Manufacturing", "Automobile Engineering", "Robotics", "HVAC"],
  },

  civil: {
    id: "civil",
    name: "Civil Engineering",
    abbreviation: "CE",
    description: "Focuses on infrastructure, construction, and environmental systems",
    curriculum: [
      {
        year: 1,
        semester1: [
          {
            id: "ma101",
            name: "Engineering Mathematics I",
            code: "MA101",
            credits: 4,
            description: "Calculus, differential equations",
            type: "core",
          },
          {
            id: "ph101",
            name: "Engineering Physics I",
            code: "PH101",
            credits: 4,
            description: "Mechanics, properties of matter",
            type: "core",
          },
          {
            id: "ch101",
            name: "Engineering Chemistry",
            code: "CH101",
            credits: 3,
            description: "Chemistry for civil engineers",
            type: "core",
          },
          {
            id: "ce101",
            name: "Engineering Graphics",
            code: "CE101",
            credits: 4,
            description: "Technical drawing, CAD",
            type: "core",
          },
          {
            id: "ce102",
            name: "Building Materials",
            code: "CE102",
            credits: 3,
            description: "Construction materials",
            type: "core",
          },
          {
            id: "hs101",
            name: "English Communication",
            code: "HS101",
            credits: 2,
            description: "Technical communication",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ma102",
            name: "Engineering Mathematics II",
            code: "MA102",
            credits: 4,
            description: "Linear algebra, vector calculus",
            type: "core",
          },
          {
            id: "ph102",
            name: "Engineering Physics II",
            code: "PH102",
            credits: 4,
            description: "Waves, heat, electricity",
            type: "core",
          },
          {
            id: "ce103",
            name: "Engineering Mechanics",
            code: "CE103",
            credits: 4,
            description: "Statics, dynamics",
            type: "core",
          },
          {
            id: "ce104",
            name: "Surveying I",
            code: "CE104",
            credits: 4,
            description: "Land surveying basics",
            type: "core",
          },
          {
            id: "ee101",
            name: "Basic Electrical Engineering",
            code: "EE101",
            credits: 3,
            description: "Electrical fundamentals",
            type: "core",
          },
          {
            id: "hs102",
            name: "Environmental Science",
            code: "HS102",
            credits: 2,
            description: "Environmental awareness",
            type: "core",
          },
        ],
      },
      {
        year: 2,
        semester1: [
          {
            id: "ma201",
            name: "Advanced Engineering Mathematics",
            code: "MA201",
            credits: 4,
            description: "Statistics, numerical methods",
            type: "core",
          },
          {
            id: "ce201",
            name: "Strength of Materials",
            code: "CE201",
            credits: 4,
            description: "Stress, strain analysis",
            type: "core",
          },
          {
            id: "ce202",
            name: "Fluid Mechanics",
            code: "CE202",
            credits: 4,
            description: "Fluid statics and dynamics",
            type: "core",
          },
          {
            id: "ce203",
            name: "Surveying II",
            code: "CE203",
            credits: 3,
            description: "Advanced surveying",
            type: "core",
          },
          {
            id: "ce204",
            name: "Construction Technology",
            code: "CE204",
            credits: 3,
            description: "Construction methods",
            type: "core",
          },
          {
            id: "ce205",
            name: "Surveying Lab",
            code: "CE205",
            credits: 2,
            description: "Field surveying",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "ce206",
            name: "Structural Analysis I",
            code: "CE206",
            credits: 4,
            description: "Analysis of determinate structures",
            type: "core",
          },
          {
            id: "ce207",
            name: "Geotechnical Engineering I",
            code: "CE207",
            credits: 4,
            description: "Soil mechanics",
            type: "core",
          },
          {
            id: "ce208",
            name: "Hydraulics",
            code: "CE208",
            credits: 4,
            description: "Open channel flow, pipe flow",
            type: "core",
          },
          {
            id: "ce209",
            name: "Concrete Technology",
            code: "CE209",
            credits: 3,
            description: "Concrete design and testing",
            type: "core",
          },
          {
            id: "cs101",
            name: "Computer Programming",
            code: "CS101",
            credits: 3,
            description: "Programming for engineers",
            type: "core",
          },
          {
            id: "ce210",
            name: "Materials Lab",
            code: "CE210",
            credits: 2,
            description: "Testing of materials",
            type: "lab",
          },
        ],
      },
      {
        year: 3,
        semester1: [
          {
            id: "ce301",
            name: "Structural Analysis II",
            code: "CE301",
            credits: 4,
            description: "Indeterminate structures",
            type: "core",
          },
          {
            id: "ce302",
            name: "Geotechnical Engineering II",
            code: "CE302",
            credits: 4,
            description: "Foundation engineering",
            type: "core",
          },
          {
            id: "ce303",
            name: "Water Resources Engineering",
            code: "CE303",
            credits: 4,
            description: "Hydrology, water management",
            type: "core",
          },
          {
            id: "ce304",
            name: "Transportation Engineering I",
            code: "CE304",
            credits: 3,
            description: "Highway engineering",
            type: "elective",
          },
          {
            id: "ce305",
            name: "Environmental Engineering I",
            code: "CE305",
            credits: 3,
            description: "Water treatment",
            type: "elective",
          },
          {
            id: "ce306",
            name: "Hydraulics Lab",
            code: "CE306",
            credits: 2,
            description: "Fluid mechanics experiments",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "ce307",
            name: "Design of Steel Structures",
            code: "CE307",
            credits: 4,
            description: "Steel structure design",
            type: "core",
          },
          {
            id: "ce308",
            name: "Design of Concrete Structures",
            code: "CE308",
            credits: 4,
            description: "RCC design",
            type: "core",
          },
          {
            id: "ce309",
            name: "Transportation Engineering II",
            code: "CE309",
            credits: 3,
            description: "Traffic engineering",
            type: "elective",
          },
          {
            id: "ce310",
            name: "Environmental Engineering II",
            code: "CE310",
            credits: 3,
            description: "Wastewater treatment",
            type: "elective",
          },
          {
            id: "ce311",
            name: "Earthquake Engineering",
            code: "CE311",
            credits: 3,
            description: "Seismic design",
            type: "elective",
          },
          {
            id: "ce312",
            name: "Structural Lab",
            code: "CE312",
            credits: 2,
            description: "Structural testing",
            type: "lab",
          },
        ],
      },
      {
        year: 4,
        semester1: [
          {
            id: "ce401",
            name: "Advanced Structural Design",
            code: "CE401",
            credits: 3,
            description: "High-rise structures",
            type: "elective",
          },
          {
            id: "ce402",
            name: "Bridge Engineering",
            code: "CE402",
            credits: 3,
            description: "Bridge design and construction",
            type: "elective",
          },
          {
            id: "ce403",
            name: "Construction Management",
            code: "CE403",
            credits: 3,
            description: "Project planning, scheduling",
            type: "elective",
          },
          {
            id: "ce404",
            name: "Engineering Economics",
            code: "CE404",
            credits: 2,
            description: "Economic analysis",
            type: "core",
          },
          {
            id: "ce405",
            name: "Major Project I",
            code: "CE405",
            credits: 4,
            description: "Capstone project",
            type: "project",
          },
          {
            id: "hs401",
            name: "Professional Ethics",
            code: "HS401",
            credits: 2,
            description: "Engineering ethics",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ce406",
            name: "Green Building Technology",
            code: "CE406",
            credits: 3,
            description: "Sustainable construction",
            type: "elective",
          },
          {
            id: "ce407",
            name: "GIS and Remote Sensing",
            code: "CE407",
            credits: 3,
            description: "Geospatial technology",
            type: "elective",
          },
          {
            id: "ce408",
            name: "Disaster Management",
            code: "CE408",
            credits: 3,
            description: "Risk assessment, mitigation",
            type: "elective",
          },
          {
            id: "ce409",
            name: "Major Project II",
            code: "CE409",
            credits: 6,
            description: "Project completion",
            type: "project",
          },
          {
            id: "hs402",
            name: "Entrepreneurship",
            code: "HS402",
            credits: 2,
            description: "Business development",
            type: "elective",
          },
        ],
      },
    ],
    specializations: [
      "Structural Engineering",
      "Geotechnical Engineering",
      "Transportation Engineering",
      "Environmental Engineering",
      "Construction Management",
    ],
  },

  chemical: {
    id: "chemical",
    name: "Chemical Engineering",
    abbreviation: "ChE",
    description: "Focuses on chemical processes, process design, and industrial chemistry",
    curriculum: [
      {
        year: 1,
        semester1: [
          {
            id: "ma101",
            name: "Engineering Mathematics I",
            code: "MA101",
            credits: 4,
            description: "Calculus, differential equations",
            type: "core",
          },
          {
            id: "ph101",
            name: "Engineering Physics I",
            code: "PH101",
            credits: 4,
            description: "Mechanics, thermodynamics",
            type: "core",
          },
          {
            id: "ch101",
            name: "General Chemistry",
            code: "CH101",
            credits: 4,
            description: "Fundamental chemistry",
            type: "core",
          },
          {
            id: "che101",
            name: "Introduction to Chemical Engineering",
            code: "CHE101",
            credits: 3,
            description: "Chemical engineering basics",
            type: "core",
          },
          {
            id: "me101",
            name: "Engineering Graphics",
            code: "ME101",
            credits: 3,
            description: "Technical drawing",
            type: "core",
          },
          {
            id: "hs101",
            name: "English Communication",
            code: "HS101",
            credits: 2,
            description: "Technical communication",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ma102",
            name: "Engineering Mathematics II",
            code: "MA102",
            credits: 4,
            description: "Linear algebra, vector calculus",
            type: "core",
          },
          {
            id: "ph102",
            name: "Engineering Physics II",
            code: "PH102",
            credits: 4,
            description: "Heat, electricity, magnetism",
            type: "core",
          },
          {
            id: "ch102",
            name: "Organic Chemistry",
            code: "CH102",
            credits: 4,
            description: "Organic compounds and reactions",
            type: "core",
          },
          {
            id: "che102",
            name: "Material and Energy Balances",
            code: "CHE102",
            credits: 4,
            description: "Process calculations",
            type: "core",
          },
          {
            id: "ee101",
            name: "Basic Electrical Engineering",
            code: "EE101",
            credits: 3,
            description: "Electrical fundamentals",
            type: "core",
          },
          {
            id: "hs102",
            name: "Environmental Science",
            code: "HS102",
            credits: 2,
            description: "Environmental awareness",
            type: "core",
          },
        ],
      },
      {
        year: 2,
        semester1: [
          {
            id: "ma201",
            name: "Advanced Engineering Mathematics",
            code: "MA201",
            credits: 4,
            description: "Statistics, numerical methods",
            type: "core",
          },
          {
            id: "che201",
            name: "Chemical Engineering Thermodynamics I",
            code: "CHE201",
            credits: 4,
            description: "Phase equilibria, properties",
            type: "core",
          },
          {
            id: "che202",
            name: "Fluid Mechanics",
            code: "CHE202",
            credits: 4,
            description: "Fluid flow in pipes and equipment",
            type: "core",
          },
          {
            id: "ch201",
            name: "Physical Chemistry",
            code: "CH201",
            credits: 4,
            description: "Chemical kinetics, thermodynamics",
            type: "core",
          },
          {
            id: "cs101",
            name: "Computer Programming",
            code: "CS101",
            credits: 3,
            description: "Programming for engineers",
            type: "core",
          },
          {
            id: "che203",
            name: "Chemistry Lab",
            code: "CHE203",
            credits: 2,
            description: "Chemical analysis",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "che204",
            name: "Chemical Engineering Thermodynamics II",
            code: "CHE204",
            credits: 4,
            description: "Chemical reaction equilibria",
            type: "core",
          },
          {
            id: "che205",
            name: "Heat Transfer",
            code: "CHE205",
            credits: 4,
            description: "Heat conduction, convection, radiation",
            type: "core",
          },
          {
            id: "che206",
            name: "Mass Transfer I",
            code: "CHE206",
            credits: 4,
            description: "Diffusion, mass transfer coefficients",
            type: "core",
          },
          {
            id: "che207",
            name: "Chemical Process Calculations",
            code: "CHE207",
            credits: 3,
            description: "Process design calculations",
            type: "core",
          },
          {
            id: "ch202",
            name: "Analytical Chemistry",
            code: "CH202",
            credits: 3,
            description: "Quantitative analysis",
            type: "core",
          },
          {
            id: "che208",
            name: "Fluid Mechanics Lab",
            code: "CHE208",
            credits: 2,
            description: "Flow measurement",
            type: "lab",
          },
        ],
      },
      {
        year: 3,
        semester1: [
          {
            id: "che301",
            name: "Mass Transfer II",
            code: "CHE301",
            credits: 4,
            description: "Distillation, extraction",
            type: "core",
          },
          {
            id: "che302",
            name: "Chemical Reaction Engineering I",
            code: "CHE302",
            credits: 4,
            description: "Reaction kinetics, reactor design",
            type: "core",
          },
          {
            id: "che303",
            name: "Process Heat Transfer",
            code: "CHE303",
            credits: 4,
            description: "Heat exchanger design",
            type: "core",
          },
          {
            id: "che304",
            name: "Instrumentation and Process Control",
            code: "CHE304",
            credits: 3,
            description: "Control systems",
            type: "elective",
          },
          {
            id: "che305",
            name: "Petroleum Refining",
            code: "CHE305",
            credits: 3,
            description: "Oil refining processes",
            type: "elective",
          },
          {
            id: "che306",
            name: "Heat Transfer Lab",
            code: "CHE306",
            credits: 2,
            description: "Heat transfer experiments",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "che307",
            name: "Chemical Reaction Engineering II",
            code: "CHE307",
            credits: 4,
            description: "Non-ideal reactors",
            type: "core",
          },
          {
            id: "che308",
            name: "Process Design and Economics",
            code: "CHE308",
            credits: 4,
            description: "Plant design, economics",
            type: "core",
          },
          {
            id: "che309",
            name: "Biochemical Engineering",
            code: "CHE309",
            credits: 3,
            description: "Bioprocesses",
            type: "elective",
          },
          {
            id: "che310",
            name: "Polymer Science",
            code: "CHE310",
            credits: 3,
            description: "Polymer chemistry and engineering",
            type: "elective",
          },
          {
            id: "che311",
            name: "Environmental Engineering",
            code: "CHE311",
            credits: 3,
            description: "Pollution control",
            type: "elective",
          },
          {
            id: "che312",
            name: "Mass Transfer Lab",
            code: "CHE312",
            credits: 2,
            description: "Separation processes",
            type: "lab",
          },
        ],
      },
      {
        year: 4,
        semester1: [
          {
            id: "che401",
            name: "Process Safety and Hazard Analysis",
            code: "CHE401",
            credits: 3,
            description: "Industrial safety",
            type: "elective",
          },
          {
            id: "che402",
            name: "Advanced Separation Processes",
            code: "CHE402",
            credits: 3,
            description: "Membrane processes",
            type: "elective",
          },
          {
            id: "che403",
            name: "Nanotechnology",
            code: "CHE403",
            credits: 3,
            description: "Nanomaterials and processes",
            type: "elective",
          },
          {
            id: "che404",
            name: "Project Management",
            code: "CHE404",
            credits: 2,
            description: "Engineering project management",
            type: "core",
          },
          {
            id: "che405",
            name: "Major Project I",
            code: "CHE405",
            credits: 4,
            description: "Capstone project",
            type: "project",
          },
          {
            id: "hs401",
            name: "Professional Ethics",
            code: "HS401",
            credits: 2,
            description: "Engineering ethics",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "che406",
            name: "Process Optimization",
            code: "CHE406",
            credits: 3,
            description: "Optimization techniques",
            type: "elective",
          },
          {
            id: "che407",
            name: "Green Chemistry",
            code: "CHE407",
            credits: 3,
            description: "Sustainable processes",
            type: "elective",
          },
          {
            id: "che408",
            name: "Industrial Chemistry",
            code: "CHE408",
            credits: 3,
            description: "Industrial chemical processes",
            type: "elective",
          },
          {
            id: "che409",
            name: "Major Project II",
            code: "CHE409",
            credits: 6,
            description: "Project completion",
            type: "project",
          },
          {
            id: "hs402",
            name: "Entrepreneurship",
            code: "HS402",
            credits: 2,
            description: "Business development",
            type: "elective",
          },
        ],
      },
    ],
    specializations: [
      "Process Engineering",
      "Petroleum Engineering",
      "Biochemical Engineering",
      "Environmental Engineering",
      "Materials Engineering",
    ],
  },

  electronics: {
    id: "electronics",
    name: "Electronics and Communication Engineering",
    abbreviation: "ECE",
    description: "Focuses on electronics, communication systems, and signal processing",
    curriculum: [
      {
        year: 1,
        semester1: [
          {
            id: "ma101",
            name: "Engineering Mathematics I",
            code: "MA101",
            credits: 4,
            description: "Calculus, differential equations",
            type: "core",
          },
          {
            id: "ph101",
            name: "Engineering Physics I",
            code: "PH101",
            credits: 4,
            description: "Mechanics, waves, optics",
            type: "core",
          },
          {
            id: "ch101",
            name: "Engineering Chemistry",
            code: "CH101",
            credits: 3,
            description: "Basic chemistry principles",
            type: "core",
          },
          {
            id: "ece101",
            name: "Electronics Fundamentals",
            code: "ECE101",
            credits: 4,
            description: "Basic electronics concepts",
            type: "core",
          },
          {
            id: "me101",
            name: "Engineering Graphics",
            code: "ME101",
            credits: 3,
            description: "Technical drawing",
            type: "core",
          },
          {
            id: "hs101",
            name: "English Communication",
            code: "HS101",
            credits: 2,
            description: "Technical communication",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ma102",
            name: "Engineering Mathematics II",
            code: "MA102",
            credits: 4,
            description: "Linear algebra, vector calculus",
            type: "core",
          },
          {
            id: "ph102",
            name: "Engineering Physics II",
            code: "PH102",
            credits: 4,
            description: "Electricity, magnetism, modern physics",
            type: "core",
          },
          {
            id: "ece102",
            name: "Circuit Analysis",
            code: "ECE102",
            credits: 4,
            description: "DC and AC circuit analysis",
            type: "core",
          },
          {
            id: "ece103",
            name: "Electronic Devices",
            code: "ECE103",
            credits: 4,
            description: "Semiconductors, diodes, transistors",
            type: "core",
          },
          {
            id: "cs101",
            name: "Programming Fundamentals",
            code: "CS101",
            credits: 3,
            description: "C programming",
            type: "core",
          },
          {
            id: "hs102",
            name: "Environmental Science",
            code: "HS102",
            credits: 2,
            description: "Environmental awareness",
            type: "core",
          },
        ],
      },
      {
        year: 2,
        semester1: [
          {
            id: "ma201",
            name: "Advanced Engineering Mathematics",
            code: "MA201",
            credits: 4,
            description: "Complex analysis, transforms",
            type: "core",
          },
          {
            id: "ece201",
            name: "Analog Electronics I",
            code: "ECE201",
            credits: 4,
            description: "Amplifiers, oscillators",
            type: "core",
          },
          {
            id: "ece202",
            name: "Digital Electronics",
            code: "ECE202",
            credits: 4,
            description: "Logic gates, combinational circuits",
            type: "core",
          },
          {
            id: "ece203",
            name: "Signals and Systems",
            code: "ECE203",
            credits: 4,
            description: "Signal analysis, system response",
            type: "core",
          },
          {
            id: "ece204",
            name: "Electromagnetic Fields",
            code: "ECE204",
            credits: 3,
            description: "Maxwell's equations",
            type: "core",
          },
          {
            id: "ece205",
            name: "Electronics Lab I",
            code: "ECE205",
            credits: 2,
            description: "Basic electronics experiments",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "ece206",
            name: "Analog Electronics II",
            code: "ECE206",
            credits: 4,
            description: "Operational amplifiers, filters",
            type: "core",
          },
          {
            id: "ece207",
            name: "Digital System Design",
            code: "ECE207",
            credits: 4,
            description: "Sequential circuits, state machines",
            type: "core",
          },
          {
            id: "ece208",
            name: "Network Analysis",
            code: "ECE208",
            credits: 4,
            description: "Network theorems, filters",
            type: "core",
          },
          {
            id: "ece209",
            name: "Probability and Random Processes",
            code: "ECE209",
            credits: 3,
            description: "Statistical signal analysis",
            type: "core",
          },
          {
            id: "ece210",
            name: "Microprocessors",
            code: "ECE210",
            credits: 3,
            description: "8085/8086 architecture",
            type: "core",
          },
          {
            id: "ece211",
            name: "Electronics Lab II",
            code: "ECE211",
            credits: 2,
            description: "Advanced electronics experiments",
            type: "lab",
          },
        ],
      },
      {
        year: 3,
        semester1: [
          {
            id: "ece301",
            name: "Communication Systems I",
            code: "ECE301",
            credits: 4,
            description: "Analog communication",
            type: "core",
          },
          {
            id: "ece302",
            name: "Digital Signal Processing",
            code: "ECE302",
            credits: 4,
            description: "DSP algorithms, filters",
            type: "core",
          },
          {
            id: "ece303",
            name: "Microcontrollers",
            code: "ECE303",
            credits: 4,
            description: "8051, ARM microcontrollers",
            type: "core",
          },
          {
            id: "ece304",
            name: "Antenna Theory",
            code: "ECE304",
            credits: 3,
            description: "Antenna design and analysis",
            type: "elective",
          },
          {
            id: "ece305",
            name: "VLSI Design",
            code: "ECE305",
            credits: 3,
            description: "IC design, VHDL",
            type: "elective",
          },
          {
            id: "ece306",
            name: "DSP Lab",
            code: "ECE306",
            credits: 2,
            description: "Signal processing experiments",
            type: "lab",
          },
        ],
        semester2: [
          {
            id: "ece307",
            name: "Communication Systems II",
            code: "ECE307",
            credits: 4,
            description: "Digital communication",
            type: "core",
          },
          {
            id: "ece308",
            name: "Control Systems",
            code: "ECE308",
            credits: 4,
            description: "Feedback control, stability",
            type: "core",
          },
          {
            id: "ece309",
            name: "Embedded Systems",
            code: "ECE309",
            credits: 3,
            description: "Real-time systems",
            type: "elective",
          },
          {
            id: "ece310",
            name: "Optical Communication",
            code: "ECE310",
            credits: 3,
            description: "Fiber optic systems",
            type: "elective",
          },
          {
            id: "ece311",
            name: "RF and Microwave Engineering",
            code: "ECE311",
            credits: 3,
            description: "High-frequency circuits",
            type: "elective",
          },
          {
            id: "ece312",
            name: "Communication Lab",
            code: "ECE312",
            credits: 2,
            description: "Communication experiments",
            type: "lab",
          },
        ],
      },
      {
        year: 4,
        semester1: [
          {
            id: "ece401",
            name: "Wireless Communication",
            code: "ECE401",
            credits: 3,
            description: "Mobile communication systems",
            type: "elective",
          },
          {
            id: "ece402",
            name: "Image Processing",
            code: "ECE402",
            credits: 3,
            description: "Digital image processing",
            type: "elective",
          },
          {
            id: "ece403",
            name: "Biomedical Electronics",
            code: "ECE403",
            credits: 3,
            description: "Medical instrumentation",
            type: "elective",
          },
          {
            id: "ece404",
            name: "Project Management",
            code: "ECE404",
            credits: 2,
            description: "Engineering project management",
            type: "core",
          },
          {
            id: "ece405",
            name: "Major Project I",
            code: "ECE405",
            credits: 4,
            description: "Capstone project",
            type: "project",
          },
          {
            id: "hs401",
            name: "Professional Ethics",
            code: "HS401",
            credits: 2,
            description: "Engineering ethics",
            type: "core",
          },
        ],
        semester2: [
          {
            id: "ece406",
            name: "IoT and Sensor Networks",
            code: "ECE406",
            credits: 3,
            description: "Internet of Things",
            type: "elective",
          },
          {
            id: "ece407",
            name: "Artificial Intelligence",
            code: "ECE407",
            credits: 3,
            description: "AI algorithms for ECE",
            type: "elective",
          },
          {
            id: "ece408",
            name: "Advanced Digital Communication",
            code: "ECE408",
            credits: 3,
            description: "Modern communication systems",
            type: "elective",
          },
          {
            id: "ece409",
            name: "Major Project II",
            code: "ECE409",
            credits: 6,
            description: "Project completion",
            type: "project",
          },
          {
            id: "hs402",
            name: "Entrepreneurship",
            code: "HS402",
            credits: 2,
            description: "Business development",
            type: "elective",
          },
        ],
      },
    ],
    specializations: [
      "Communication Systems",
      "VLSI Design",
      "Signal Processing",
      "Embedded Systems",
      "RF Engineering",
    ],
  },
}

export function getAllBranches(): EngineeringBranch[] {
  return Object.values(engineeringCurriculum)
}

export function getBranchById(branchId: string): EngineeringBranch | undefined {
  return engineeringCurriculum[branchId]
}

export function getCoursesByBranchAndYear(branchId: string, year: number): Course[] {
  const branch = getBranchById(branchId)
  if (!branch) return []

  const yearData = branch.curriculum.find((c) => c.year === year)
  if (!yearData) return []

  return [...yearData.semester1, ...yearData.semester2]
}

export function getAllCoursesByBranch(branchId: string): Course[] {
  const branch = getBranchById(branchId)
  if (!branch) return []

  return branch.curriculum.flatMap((year) => [...year.semester1, ...year.semester2])
}

export function searchCourses(query: string, branchId?: string): Course[] {
  const branches = branchId ? [getBranchById(branchId)] : getAllBranches()
  const allCourses = branches.filter(Boolean).flatMap((branch) => getAllCoursesByBranch(branch!.id))

  return allCourses.filter(
    (course) =>
      course.name.toLowerCase().includes(query.toLowerCase()) ||
      course.description.toLowerCase().includes(query.toLowerCase()) ||
      course.code.toLowerCase().includes(query.toLowerCase()),
  )
}
